### ISSUE TITLE
Insert generated text into docstring?

### ISSUE THREAD

**Issue by jgostick** [Chilipp/docrep#14]
This is more a feature request than an issue...

I would like to inject some programmatically generated text into my docstrings, and based on the awesomeness of docrep, I"m sure you know how to do it.

For instance, consider the following docstring:

```
"""
This is a function docstring

"{0}"

More docstring
""".format(('insert this'))
```

This is a valid python string and the text will be inserted at the {0} location.  But in spyder and sphinx, this does not work.  Since docrep is able to inject text that DOES work with spyder and sphinx, I wonder if you have any suggestions?  

BTW, my actually use case is to inject a generated table of functions into the docstring for a module __init__, so that an up-to-date list of all functions can be displayed in spyder / sphinx without me having to manually maintain the list as functions are added/removed/renamed etc.

**Comment by Chilipp** [comment]
hi @jgostick ! Hmm, I think I know what you mean. You want, while typing in the Spyder editor window and using the code introspection, that the formatted docstring is shown in the help explorer. Do I get you right?

However, this does *not* work with docrep as you can see in the screenshot below

![image](https://user-images.githubusercontent.com/9960249/52169057-9f8a4d80-2732-11e9-8959-7c7cec0c39ff.png)


Here I use the code introspection on the `keys` method to show it's docstring in spyders help. The `keys` method thereby uses some docstring parts from another method and they are inserted using the `dostrings.dedent` decorator.
 
However, spyder does not really import the module to get the docstring from the object. Instead it uses some other functionality in order to avoid large loading times. Hence, the decorator `@docstrings.dedent` in the above screenshot is not executed and spyder does not know that the docstring of `keys` actually looks different.

Within a normal sphinx documentation, this is different, since the `autodoc` extension imports the modules that are to be documented.

Therefore, unfortunately, I don't have any idea about how to use your formatted docstring within spyder.

**Comment by jgostick** [comment]
thanks for your time!

**Comment by Chilipp** [comment]
You're welcome. Sorry I could not help.

Good luck!
